//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladište
    {
        public int ID_Skladista { get; set; }
        public int ID_Proizvoda { get; set; }
        public Nullable<int> Kolicina { get; set; }
    
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
