//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbe
    {
        public int ID_Narudzbe { get; set; }
        public int ID_Kupca { get; set; }
        public int ID_Proizvoda { get; set; }
        public int ID_Dostave { get; set; }
    
        public virtual Dostava Dostava { get; set; }
        public virtual Kupci Kupci { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
